### ISSUE TITLE
1.Introduccion

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd#1]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/d36b0c5f-3a9a-4429-859a-6f6a7fe627af)

![Image](https://github.com/tectijuana/interfaz/assets/2523851/60108175-be44-446e-8e11-143560b98b3d)

# Aviso para Estudiantes: Uso de Markdown en Repositorios de GitHub Classroom

## Estimados estudiantes,

En el marco de nuestras actividades académicas en **GitHub Classroom**, queremos destacar la importancia del uso de **Markdown** para la documentación y presentación de sus proyectos de forma clara y eficaz. Markdown es un lenguaje de marcado ligero que facilita la conversión de texto plano en HTML, lo que permite crear documentos estructurados y fáciles de leer directamente en GitHub.

### **¿Por qué utilizar Markdown?**

- **Claridad y Estructura:** Permite organizar la información de manera lógica, utilizando encabezados, listas, enlaces e imágenes, lo que facilita su comprensión.
- **Sencillez de Uso:** Su facilidad de aprendizaje y uso permite que se concentren en el contenido de su documentación, sin preocuparse por la complejidad del formato.
- **Compatibilidad:** Los documentos creados con Markdown son compatibles con diversas plataformas y herramientas, asegurando que su trabajo sea accesible en diferentes contextos.
- **Profesionalismo:** Un manejo adecuado de Markdown refleja profesionalidad y atención al detalle, habilidades muy valoradas en el ámbito tecnológico.

### **Directrices para el uso de Markdown en sus proyectos:**

- **README.md:** Es indispensable incluir un archivo `README.md` en la raíz de cada repositorio, donde describan el propósito del proyecto, características, instrucciones de instalación, dependencias y cualquier otra información pertinente.
- **Documentación del Código:** Utilicen Markdown para documentar su código, especialmente en scripts complejos, funciones y módulos, para explicar su lógica y uso.
- **Informes y Reflexiones:** Empleen Markdown para estructurar informes o reflexiones, utilizando títulos, subtítulos, listas y citas para mejorar la legibilidad y comprensión.
- **Inclusión de Elementos Multimedia:** Aprovechen las capacidades de Markdown para incluir imágenes, gifs y enlaces a videos que complementen sus explicaciones o demostraciones.

### **Recursos para aprender y mejorar su uso de Markdown:**

- [Guía Básica de Markdown](https://www.markdownguide.org/basic-syntax/)
- [Dominando Markdown en GitHub](https://guides.github.com/features/mastering-markdown/)
- [Tutorial Interactivo de Markdown](https://www.markdowntutorial.com/)

Los animamos a familiarizarse con Markdown y a utilizarlo de manera efectiva en sus proyectos. El dominio de esta herramienta no solo mejorará la calidad de sus entregas, sino que también les proporcionará una habilidad valiosa para su futuro profesional.

### **Atentamente,**

_Rene Solis  Depto. Sistemas y Computacion_

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/9efe1f31-6bae-4071-853e-a3d962fcb087)



![Image](https://github.com/tectijuana/interfaz/assets/2523851/79e46cc3-cf90-4c53-ba17-6b5d69c9aeca) Link GH Classroom: https://classroom.github.com/a/rpPlA_3E    👈 

# Práctica: Uso de ASCIINEMA.org en la Terminal del Servidor de remoto para las actividades generales de esta induccion.

ENLACES:
https://asciinema.org/
https://interorganic.com.ar/josx/asciinema.pdf
https://picodotdev.github.io/blog-bitix/2015/09/grabar-y-compartir-video-de-la-terminal-con-asciinema/

## Objetivos
- Familiarizarse con la terminal de AWS, conectarse a una sesion remota e interactuar con el OS.
- Aprender a grabar sesiones de terminal con ASCIINEMA.
- Desarrollar y demostrar habilidades genericas multi-nivel programación en la terminal.
- Documentar y explicar el código y procesos de programación y gestion del servidor.

## Practicas
1. Configura tu entorno de servidor en AWS y prepáralo para la grabación.
2. Utiliza ASCIINEMA para grabar una sesión de terminal ejecutando tu script de programación. Asegúrate de incluir comentarios explicativos en tu código.
3. Edita tu grabación para incluir tu nombre y datos generales al inicio o final de la sesión.
4. Sube el enlace de tu grabación de ASCIINEMA a este repositorio de GitHub Classroom.

## Rúbrica de Evaluación
### Dominio Técnico (40 Puntos)
- Uso de la terminal y comandos básicos: 10 Puntos
- Complejidad o repaso del script de programación o secuencia solicitada en clase: 20 Puntos
- Claridad en los comentarios del código, de la demostracion que esta ejerciendo: 10 Puntos

### Calidad de la Grabación (30 Puntos)
- Claridad y fluidez de la sesión: 15 Puntos
- Personalización y creatividad el muestreo de plantilla: 15 Puntos

### Documentación y Explicación en MARKDOWN (30 Puntos)
- Descripción del proyecto en GitHub con sus etiquetado Markdown: 10 Puntos
- Explicación en la grabación Markdown: 10 Puntos
- Reflexión y conclusiones Markdown:  10 Puntos

## Entrega
Sube el enlace de tu grabación de ASCIINEMA a este repositorio antes de la fecha límite. Asegúrate de seguir todas las instrucciones y criterios de evaluación.

Por cuestiones climaticas se entrega el miercoles de la prox. semana

¡Buena suerte!

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/a5f16202-abf3-4a12-8c34-f9eae53a6367)

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/a5f16202-abf3-4a12-8c34- f9eae53a6367)

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/interfaz/assets/2523851/a5f16202-abf3-

**Comment by Danielusuario** [comment]
https://asciinema.org/a/l7SPDLAT5HIBpefxE2LP7uNKX

**Comment by Kalis-Be** [comment]
https://gist.github.com/Kalis-Be/f088c9ec01c1df5a769cfb11414685a1
