### ISSUE TITLE
2.0 Exposiciones de Patrones GoF y Complementarios

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd#10]
![Image](https://github.com/tectijuana/pdd/assets/2523851/1da3d21e-e815-43cf-9224-167519bf3b8d)

| Tema | Categoría | Descripción |
|------|------------|--------------|
| Patrón Singleton | Patrones de Creación | Asegura que una clase sólo tenga una instancia y proporciona un punto de acceso global a ella. |
| Patrón Fábrica | Patrones de Creación | Define una interfaz para crear objetos, permitiendo que las subclases decidan qué clase instanciar. |
| Patrón Observador | Patrones de Comportamiento | Define una relación uno-a-muchos entre objetos, de modo que cuando un objeto cambia de estado, se notifica a todos los dependientes. |
| Patrón Decorador | Patrones de Estructura | Añade responsabilidades a un objeto dinámicamente, proporcionando una alternativa flexible a la herencia para extender funcionalidades. |
| Patrón Proxy | Patrones de Estructura | Proporciona un objeto sustituto que controla el acceso a otro objeto, actuando como intermediario. |
| Patrón Adapter | Patrones de Estructura | Convierte la interfaz de una clase en otra interfaz que el cliente espera, permitiendo que clases con interfaces incompatibles trabajen juntas. |
| Patrón Fachada | Patrones de Estructura | Proporciona una interfaz unificada para un conjunto de interfaces en un subsistema, definiendo una interfaz de nivel superior que facilita el uso del subsistema. |
| Patrón Composite | Patrones de Estructura | Compone objetos en estructuras de árbol para representar jerarquías parte-todo, permitiendo que los clientes traten de manera uniforme objetos individuales y compuestos. |
| Patrón Cadena de Responsabilidad | Patrones de Comportamiento | Permite que varios objetos procesen una solicitud, pasándola por una cadena hasta que un objeto la gestione. |
| Patrón Comando | Patrones de Comportamiento | Encapsula una operación en un objeto, permitiendo parametrizar clientes con diferentes solicitudes y soportar operaciones reversibles. |
| Patrón Iterador | Patrones de Comportamiento | Proporciona un modo de acceder secuencialmente a los elementos de una colección sin exponer su representación interna. |
| Patrón Mediador | Patrones de Comportamiento | Define un objeto que encapsula las interacciones entre un conjunto de objetos, promoviendo un bajo acoplamiento al evitar que los objetos se refieran unos a otros explícitamente. |
| Patrón Memento | Patrones de Comportamiento | Captura y externaliza el estado interno de un objeto sin violar el encapsulamiento, para poder restaurarlo más tarde. |
| Patrón Estado | Patrones de Comportamiento | Permite que un objeto modifique su comportamiento cuando cambia su estado interno. |
| Patrón Estrategia | Patrones de Comportamiento | Define una familia de algoritmos, encapsula cada uno y los hace intercambiables, permitiendo que el algoritmo varíe independientemente de los clientes que lo utilizan. |
| Patrón Plantilla de Método | Patrones de Comportamiento | Define el esqueleto de un algoritmo en una operación, permitiendo que las subclases sobrescriban ciertos pasos del algoritmo sin cambiar su estructura. |
| Patrón Visitor | Patrones de Comportamiento | Representa una operación a realizar sobre los elementos de una estructura de objetos, permitiendo definir una nueva operación sin cambiar las clases de los elementos sobre los que opera. |
| Patrón Builder | Patrones de Creación | Separa la construcción de un objeto complejo de su representación, de modo que el mismo proceso de construcción pueda crear diferentes representaciones. |
| Patrón Prototipo | Patrones de Creación | Permite la creación de nuevos objetos clonando objetos existentes, en lugar de crearlos desde cero. |
| Patrón Puente | Patrones de Estructura | Desacopla una abstracción de su implementación, de modo que ambas puedan variar independientemente. |
| Patrón Flyweight | Patrones de Estructura | Utiliza el compartimento para soportar de forma eficiente grandes cantidades de objetos de grano fino. |
| Patrón Módulo | Patrones de Estructura | Divide las responsabilidades de un programa en bloques separados de funcionalidad reutilizable. |
| Patrón Paso de Mensajes | Patrones de Integración y Mensajería | Permite que los componentes de un sistema distribuido se comuniquen a través del paso de mensajes. |
| Patrones de Integración Empresarial | Patrones de Integración y Mensajería | Patrones como Mensaje, Patrón de Datos Transferidos y Patrón de Enrutamiento de Mensajes facilitan la integración de aplicaciones y servicios. |
| Patrones de Gestión de Transacciones | Patrones de Integración y Mensajería | Patrones como Transacción Compensatoria y Ejecución Atómica gestionan transacciones en sistemas distribuidos. |
| Patrones de Mensajería | Patrones de Integración y Mensajería | Patrones como Mensajería Punto a Punto y Publicación/Suscripción gestionan el envío y recepción de mensajes. |
| Patrones de Observación | Patrones de Administración de Sistemas | Patrones como Sonda y Patrulla facilitan la monitorización y administración de sistemas distribuidos. |
| Patrones de Administración de Recursos | Patrones de Administración de Sistemas | Patrones como Adquisición de Recursos y Agrupación de Recursos gestionan recursos en sistemas concurrentes. |
| Patrones de Planificación | Patrones de Administración de Sistemas | Patrones como Planificador de Procesos y Planificador de Hilos gestionan la planificación de tareas y procesos. |
| Patrones de Tolerancia a Fallos | Patrones de Administración de Sistemas | Patrones como Reinicio, Balanceo de Carga y Circuito Abierto mejoran la tolerancia a fallos de un sistema. |
| Patrones de Caché | Patrones de Rendimiento | Patrones como Caché Aparte y Caché de Transferencia aumentan el rendimiento almacenando datos en caché. |
| Patrón Reactor | Patrones de Concurrencia y Paralelismo | Define un servicio manejador que acepta múltiples solicitudes concurrentes y las despacha a manejadores de solicitudes. |
| Patrón Tubería y Filtros | Patrones de Integración y Procesamiento | Divide un proceso en una serie de pasos secuenciales, donde la salida de un paso se convierte en la entrada del siguiente. |
| Patrón Blackboard | Patrones de Coordinación | Proporciona una pizarra central como un espacio de trabajo compartido para ensamblar soluciones a problemas complejos. |
| Patrón Especificación | Patrones de Consulta | Reencapsula la lógica de consultas para construir expresiones de búsqueda complejas. |
| Patrón Objeto Nulo | Patrones de Objetos | Proporciona un objeto nulo en lugar de punteros nulos, para evitar comprobaciones de nulidad repetitivas. |
| Patrón Cortina | Patrones de Objetos | Oculta objetos complejos, acoplados y volátiles detrás de una interfaz simple. |
| Patrón Pila de Memorización | Patrones de Rendimiento | Almacena cálculos costosos y devuelve el resultado almacenado en caché cuando se encuentran entradas duplicadas. |
| Patrón Doble Búfer | Patrones de Concurrencia y Paralelismo | Utiliza dos búferes para minimizar el parpadeo y mejorar el rendimiento en entornos multihilo. |
| Patrón Encadenamiento de Método | Patrones de Interfaz | Permite la construcción de objetos mediante la concatenación de múltiples llamadas a métodos en una única instrucción. |
| Patrón Objeto de Transferencia de Datos (DTO) | Patrones de Integración y Mensajería | Transfiere datos entre subsistemas a través de objetos simples que no contienen lógica de negocio. |
| Patrón Mapeo de Objetos Relacionales (ORM) | Patrones de Persistencia | Mapea objetos en memoria a una base de datos relacional, ocultando los detalles de la persistencia. |
| Patrón Inyección de Dependencias | Patrones de Construcción de Software | Invierte el control para resolver las dependencias entre objetos. |
| Patrón Repositorio | Patrones de Persistencia | Abstrae el acceso a los datos, ocultando los detalles de mapeo entre el dominio y el modelo de datos. |
| Patrón Fachada de Servicios | Patrones de Integración y Mensajería | Proporciona una interfaz simplificada para un conjunto de servicios, ocultando su complejidad interna. |

Esta tabla proporciona una categorización de los temas de patrones de diseño, junto con una descripción detallada de cada uno. Esto ayudará a la elección del tema exponer y comprender mejor la función con el propósito de cada patrón. Las categorías incluyen patrones de creación, estructura, comportamiento, integración y mensajería, administración de sistemas, rendimiento, concurrencia y paralelismo, coordinación, consulta, objetos, interfaz, persistencia, y construcción de software.

---

ENTREGABLES:

1. Es libre la herramienta solo por favor de depositar el PDF para acceder a revisar el material.
2. Enviar a iDOCEO para la evaluaciónn

NOTA: Garantizar que estén en las 2 plataformas, esta para referencia del MUNDO, recuerde que un mundo nos observa y google nos indexa, entreguemos calidad en los contenidos.

![Image](https://github.com/tectijuana/pdd/assets/2523851/f6202b43-46c0-4cc5-86cb-a1f8e40bda0a)

Orden de exposición es de acuerdo a la lista de selección siguiente.

**Comment by IoTeacher** [comment]
# Ser tan amablemente de seleccionar un patrón a exponer, viene expandidos otros patrones a parte de los clasicos GoF (gang of four) para todo el grupo.
# EVITAR DUPLICADOS, lista le permite evitarlo

**Comment by keyemsi** [comment]
pido Patrón Singleton, acosta gutierrez

**Comment by Kalis-Be** [comment]
patrón de fábrica

**Comment by RogelioCR311** [comment]
Patrón modulo

**Comment by YabukiD** [comment]
patrón decorador

**Comment by calonch98** [comment]
Patrón estado

**Comment by SergioMSR09** [comment]
Patrón Observador

**Comment by BearNX** [comment]
Patron Cortina

**Comment by Beniez-paola** [comment]
Patrón Estrategia

**Comment by CarlosMolinaR** [comment]
patrones de cache

**Comment by LuisM935** [comment]
Patrones de caché.

**Comment by Beniez-paola** [comment]
Patron Estrategia

**Comment by IrvinMP** [comment]
Patron Adapter

**Comment by 03Juan2001** [comment]
Patrones de Tolerancia a Fallos

**Comment by SergioEstrada14** [comment]
Patrones de Tolerancia a Fallos

**Comment by GabrielHernandezZam** [comment]
Patron comando

**Comment by DanielGarciaITT** [comment]
Patrón Reactor

**Comment by migueszitle111** [comment]
Patrones de Mensajería

**Comment by SergioEstrada14** [comment]
Patrón Objeto Nulo

**Comment by Barny-Claus** [comment]
Patrón Fábrica

**Comment by SergioSG0** [comment]
Patrón Paso de Mensajes

**Comment by MariaRamosOrtiz** [comment]
Patrón Paso de Mensajes

**Comment by DamianRS-TEC** [comment]
Patrón de Caché

**Comment by AdrianSR30** [comment]
Patrón Flyweight

**Comment by MariaRamosOrtiz** [comment]
Patrón Tubería y Filtros

**Comment by Richierl** [comment]
Patrón Blackboard

**Comment by AlvarezKevinDaniel** [comment]
## Expositor 25
Patron memento

**Comment by miguelbct** [comment]
Patrón Builder.

**Comment by denysshdzp** [comment]
Patrón Especificación

**Comment by EduardoGV117** [comment]
#EXPOSITOR 29 

Pido Patrón Doble Búfer

**Comment by Barny-Claus** [comment]
Encadenamiento de Método

**Comment by victormillan19** [comment]
EXPOSITOR 30 
Patron adapter

**Comment by Mildgwey** [comment]
Patrones de Tolerancia a Fallos

**Comment by YuridiaSCH** [comment]
Patrón Puente

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/pdd/assets/2523851/f450c81c-74c4-4f3c-9ff8-5751af7d8b0d)

**Comment by IoTeacher** [comment]
![image](https://github.com/tectijuana/pdd/assets/2523851/efeeea4e-45bb-40a8-b0f6-bebc310dd89f)

**Comment by VaneMG** [comment]
Patrón Repositorio

**Comment by DrPepperFan** [comment]
# **Expositor 34**
Patrón repositorio

**Comment by GeraMx0** [comment]
# Expositor 35

Patrón Inyección de Dependencias

**Comment by bugalox** [comment]
Patrón Especificación

**Comment by SalvadorEliLopezPartida** [comment]
Patrón Objeto de Transferencia de Datos (DTO)

**Comment by Danielusuario** [comment]
Patrones de Planificación
