### ISSUE TITLE
Listado  de Proyectos Finales del Curso

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd#2]
| Nº | Categoría                            | Proyecto/Prototipo                                         | Desarrollador | Objetivo General                                                                                         |
|----|--------------------------------------|------------------------------------------------------------|---------------|----------------------------------------------------------------------------------------------------------|
| 1  | Inteligencia Artificial              | Generador de Música basado en IA                            |    [DrPepperFan](https://github.com/DrPepperFan)           | Desarrollar un sistema capaz de componer música original utilizando algoritmos de aprendizaje automático.|
| 2  | Ciberseguridad                       | Plataforma de Entrenamiento en Ciberseguridad con Gamificación |   [JesusMeiker](https://github.com/JesusMeiker)         | Crear una plataforma interactiva para enseñar conceptos de ciberseguridad mediante juegos y retos.       |
| 3  | Tecnologías Inmersivas               | Simulador de Realidad Virtual para Entrenamiento de Cirugías |              | Implementar un simulador en VR para entrenar a estudiantes de medicina en procedimientos quirúrgicos.    |
| 4  | Tecnología Blockchain                | Sistema de Votación Seguro basado en Blockchain             |   [AldoMon99](https://github.com/AldoMon99)            | Diseñar un sistema de votación electrónica seguro y transparente utilizando tecnología blockchain.       |
| 5  | Internet de las Cosas (IoT)          | Sistema de Monitoreo Ambiental IoT para Ciudades Inteligentes |     [Barny-Claus](https://github.com/Barny-Claus)       | Construir un sistema IoT para monitorear y gestionar la calidad ambiental en ciudades inteligentes.      |
| 6  | Big Data                             | Herramienta de Visualización de Datos para Análisis de Redes Sociales |   [calonch98](https://github.com/calonch98)   | Desarrollar una herramienta que permita visualizar y analizar grandes volúmenes de datos de redes sociales. |
| 7  | Robótica                             | Kit de Robótica Educativa DIY con Interfaz de Programación Visual |         | Crear un kit de robótica educativa que permita a los usuarios construir y programar sus propios robots.  |
| 8  | Computación en la Nube               | Plataforma Cloud para Colaboración en Proyectos de Software |    [miguelbct](https://github.com/miguelbct)          | Implementar una plataforma en la nube que facilite la colaboración en tiempo real en proyectos de software.|
| 9  | Desarrollo de Software               | Framework para Desarrollo Rápido de Aplicaciones Móviles Multiplataforma | [GabrielHernandezZam](https://github.com/GabrielHernandezZam) | Crear un framework que agilice el desarrollo de aplicaciones móviles compatibles con múltiples plataformas.|
| 10 | Machine Learning                     | Sistema de Recomendación Personalizada para E-Learning      |   [IrvinMP](https://github.com/IrvinMP)            | Desarrollar un sistema de recomendación que personalice el aprendizaje electrónico según las necesidades del usuario.|
| 11 | Análisis Predictivo                  | Modelo Predictivo para la Detección Temprana de Enfermedades |   [SergioMSR09](https://github.com/SergioMSR09)           | Construir un modelo predictivo que utilice datos de salud para la detección temprana de enfermedades.    |
| 12 | Visión Computacional                 | Aplicación para el Reconocimiento de Especies de Plantas mediante Imágenes | | Desarrollar una aplicación que identifique especies de plantas a partir de fotos utilizando visión computacional.|
| 13 | Seguridad de Datos                   | Herramienta de Análisis Forense Digital para Redes Corporativas |          | Implementar una herramienta de análisis forense para investigar y mitigar incidentes de seguridad en redes corporativas.|
| 14 | Redes Neuronales                     | Simulador de Redes Neuronales para Experimentación Educativa |   [GeraMx0](https://github.com/GeraMx0)          | Crear un simulador interactivo para facilitar la comprensión y experimentación con redes neuronales.     |
| 15 | Computación Cuántica                 | Introducción a la Programación de Algoritmos Cuánticos       |               | Desarrollar habilidades en la programación de algoritmos cuánticos para resolver problemas complejos.     |
| 16 | Desarrollo Web                       | Generador de Sitios Web Dinámicos con Tecnologías JAMstack (o frameworks modernos)  | [AlvarezKevinDaniel](https://github.com/AlvarezKevinDaniel)              | Construir una herramienta para generar sitios web dinámicos y estáticos utilizando tecnologías JAMstack. |
| 17 | Sistemas Embebidos                   | Plataforma de Desarrollo para Wearables de Salud Personalizados |  [CruzEVM](https://github.com/CruzEVM)        | Diseñar una plataforma para el desarrollo de dispositivos wearables personalizados orientados a la salud.|
| 18 | Inteligencia de Negocios             | Dashboard Interactivo para Análisis de Tendencias de Mercado |   [Jyuls](https://github.com/Jyuls)           | Implementar un dashboard interactivo que permita a las empresas analizar tendencias de mercado en tiempo real.|
| 19 | Automatización de Procesos           | Bot de Automatización para Procesos Administrativos         |  [bugalox](https://github.com/bugalox)             | Desarrollar un bot que automatice tareas administrativas rutinarias, mejorando la eficiencia operativa.  |
| 20 | Realidad Aumentada                   | Aplicación Educativa con Realidad Aumentada para Historia   |     [BearNX](https://github.com/BearNX)          | Crear una aplicación educativa que utilice realidad aumentada para enseñar historia de manera interactiva.|
| 21 | Reconocimiento de Patrones           | Sistema de Identificación de Patrones en Datos Genéticos    |               | Desarrollar un sistema que identifique patrones en datos genéticos para apoyar la investigación biomédica.|
| 22 | Interfaces Humano-Computadora        | Sistema de Control por Gestos para Aplicaciones Domóticas   |   [SergioEstrada14](https://github.com/SergioEstrada14)            | Implementar un sistema de control por gestos para mejorar la interacción con dispositivos domóticos.     |
| 23 | Procesamiento de Lenguaje Natural    | Asistente Virtual para Soporte Técnico con NLP              |   [Beniez-paola](https://github.com/Beniez-paola)            | Crear un asistente virtual que utilice NLP para proporcionar soporte técnico eficiente y personalizado.  |
| 24 | Criptografía                         | Herramienta de Criptografía Asimétrica para Mensajería Segura |             | Desarrollar una herramienta que utilice criptografía asimétrica para asegurar la privacidad de la mensajería.|
| 25 | Análisis de Sentimientos             | Plataforma de Análisis de Sentimientos en Tiempo Real para Marcas | [Mildgwey](https://github.com/Mildgwey)       | Implementar una plataforma que analice en tiempo real los sentimientos del público hacia marcas en redes sociales.|
| 26 | Tecnologías de Asistencia            | Dispositivo Asistente para Personas con Discapacidad Visual  |   [denysshdzp](https://github.com/denysshdzp)            | Diseñar un dispositivo asistente que mejore la autonomía y calidad de vida de personas con discapacidad visual.|
| 27 | Sistemas Distribuidos                | Framework para el Desarrollo de Aplicaciones Descentralizadas |             | Crear un framework que facilite el desarrollo de aplicaciones descentralizadas en sistemas distribuidos.  |
| 28 | Computación Afectiva                 | Sistema de Detección de Emociones en Vídeos Educativos      |   [AdrianSR30](https://github.com/AdrianSR30)            | Desarrollar un sistema que detecte emociones en vídeos educativos para mejorar la experiencia de aprendizaje.|
| 29 | Gamificación                         | Plataforma de Aprendizaje de Matemáticas con Gamificación   |  [DanielGarciaITT](https://github.com/DanielGarciaITT)             | Implementar una plataforma que utilice gamificación para hacer el aprendizaje de matemáticas más atractivo.|
| 30 | Reconocimiento Facial                | Sistema de Asistencia mediante Reconocimiento Facial        |    [RogelioCR311](https://github.com/RogelioCR311)           | Desarrollar un sistema de asistencia basado en reconocimiento facial para mejorar la seguridad y accesibilidad.|
| 31 | Optimización                         | Herramienta de Optimización de Rutas Logísticas             |  [CarlosMolinaR](https://github.com/CarlosMolinaR)             | Crear una herramienta que optimice rutas logísticas para mejorar la eficiencia en la entrega de productos.|
| 32 | Computación Gráfica                  | Motor de Renderizado 3D para Juegos Indie                   |   [LuisM935](https://github.com/LuisM935)            | Desarrollar un motor de renderizado 3D que permita a los desarrolladores indie crear juegos visualmente impresionantes.|
| 33 | Modelado de Datos                    | Herramienta de Diseño y Simulación de Bases de Datos NoSQL  |  [Kalis-Be](https://github.com/Kalis-Be)              | Implementar una herramienta para el diseño y simulación de bases de datos NoSQL para aplicaciones escalables.|
| 34 | Redes Ad-hoc                         | Prototipo de Red Ad-hoc para Comunicación en Áreas Remotas  |               | Desarrollar un prototipo de red ad-hoc para facilitar la comunicación en áreas remotas sin infraestructura de red.|
| 35 | Internet de las Cosas (IoT)          | Sistema IoT para Gestión Inteligente de Residuos            |               | Construir un sistema IoT que optimice la gestión de residuos en ciudades, mejorando la sostenibilidad urbana.|
| 36 | Inteligencia Artificial              | Sistema de Tutoría Inteligente para Aprendizaje de Idiomas  |     [VaneMG](https://github.com/VaneMG)          | Desarrollar un sistema de tutoría inteligente que personalice la enseñanza de idiomas basándose en IA.     |
| 37 | Ciberseguridad                       | Plataforma de Entrenamiento en Seguridad Informática con Retos |  [YabukiD](https://github.com/YabukiD)         | Crear una plataforma que ofrezca retos prácticos para mejorar las habilidades en seguridad informática.    |
| 38 | Tecnologías Inmersivas               | Aplicación de Realidad Mixta para Diseño de Interiores      |  [YuridiaSCH](https://github.com/YuridiaSCH)             | Implementar una aplicación de realidad mixta que permita a los usuarios diseñar y visualizar interiores de manera interactiva.|
| 39 | Tecnología Blockchain                | Plataforma de Intercambio de Activos Digitales              | [Danielusuario](https://github.com/Danielusuario)              | Desarrollar una plataforma segura para el intercambio de activos digitales utilizando blockchain.         |
| 40 | Big Data                             | Sistema de Análisis de Grandes Volúmenes de Datos Meteorológicos |   [keyemsi](https://github.com/keyemsi)       | Construir un sistema capaz de procesar y analizar grandes volúmenes de datos meteorológicos para predecir patrones climáticos.|
| 41 | Logístico                             | Sistema de Monitoreo y Gestión de Flotillas Vehiculares       |               | Desarrollar un sistema de información, monitoreo y geolocalización de rutas vehiculares de flotillas. |
| 42 | Computación en la Nube               | Servicio de Backup y Recuperación de Datos en la Nube       |     [Richierl](https://github.com/Richierl)          | Implementar un servicio en la nube para el backup y recuperación de datos, asegurando la continuidad del negocio.|
| 43 | Desarrollo de Software               | Herramienta de Pruebas Automatizadas para Aplicaciones Web  |   [03Juan2001](https://github.com/03Juan2001)            | Crear una herramienta que automatice las pruebas de aplicaciones web, mejorando la calidad y eficiencia del desarrollo.|
| 44 | Machine Learning                     | Modelo de ML para la Predicción de Tendencias de Moda       |   [Gibrahn](https://github.com/Gibrahn)            | Desarrollar un modelo de machine learning que prediga tendencias de moda, apoyando a diseñadores y minoristas.|
| 45 | Análisis Predictivo                  | Sistema de Alerta Temprana para Fenómenos Naturales         |   [MariaRamosOrtiz](https://github.com/MariaRamosOrtiz)            | Construir un sistema de alerta temprana que utilice análisis predictivo para prevenir desastres naturales. |
| 46 | Visión Computacional                 | Sistema de Navegación Autónoma para Vehículos Pequeños      |    [DamianRS-TEC](https://github.com/DamianRS-TEC)           | Desarrollar un sistema de navegación autónoma para vehículos pequeños utilizando técnicas de visión computacional.|
| 47 | Seguridad de Datos                   | Solución de Gestión de Identidades y Accesos                |   [migueszitle111](https://github.com/migueszitle111)            | Implementar una solución que gestione de manera segura las identidades y accesos en sistemas informáticos.|
| 48 | Redes Neuronales                     | Aplicación para la Creación de Arte Generativo con Redes Neuronales |  [Daniel-Eriberto-ZB](https://github.com/Daniel-Eriberto-ZB)     | Crear una aplicación que utilice redes neuronales para generar obras de arte digitales únicas.            |
| 49 | Computación Cuántica                 | Simulaciones Cuánticas para la Investigación en Física      |               | Desarrollar simulaciones cuánticas que apoyen la investigación y comprensión de fenómenos físicos complejos.|
| 50 | Desarrollo Web                       | Plataforma Web para la Co-creación de Proyectos Artísticos  | [SergioSG0](https://github.com/SergioSG0)              | Implementar una plataforma web que facilite la colaboración y co-creación de proyectos artísticos en línea.|

**Comment by IoTeacher** [comment]
![](https://r73.cooltext.com/rendered/cooltext452649001125264.png)

**Comment by Barny-Claus** [comment]
Internet de las Cosas (IoT)

**Comment by AldoMon99** [comment]
Sistema de Votación Seguro basado en Blockchain

**Comment by Gibrahn** [comment]
<html>
<body>

Modelo de ML para la Predicción de Tendencias de Moda
--



</body>
</html>

**Comment by Jyuls** [comment]
Tecnología Blockchain

**Comment by DamianRS-TEC** [comment]
46 Visión Computacional

**Comment by CruzEVM** [comment]
Sistemas Embebidos
Cruz Valadez

**Comment by denysshdzp** [comment]
26. Tecnologías de Asistencia

**Comment by DanielGarciaITT** [comment]
29 Gamificacion

**Comment by GabrielHernandezZam** [comment]
9 desarrollo de software

**Comment by bugalox** [comment]
Automatización de Procesos

Alejandro Martienz Reyes 20210593

**Comment by IrvinMP** [comment]
20. Realidad aumentada

**Comment by RogelioCR311** [comment]
30 Sistema de Asistencia mediante Reconocimiento Facial

**Comment by AdrianSR30** [comment]
30. Reconocimiento facial
Solis Ruiz Adrian

**Comment by Jyuls** [comment]
18 Inteligencia de Negocios

**Comment by SergioMSR09** [comment]
11. Análisis Predictivo
Soriano Rios Sergio Miguel

**Comment by Richierl** [comment]
42 Computación en la nube

**Comment by Beniez-paola** [comment]
23 Procesamiento de lenguaje natural

**Comment by DrPepperFan** [comment]
Generador de Música basado en IA
Gonzalez Valenzuela Exxon Alejandro #20210573

**Comment by Danielusuario** [comment]
39 Tecnología Blockchain

**Comment by calonch98** [comment]
6 Big Data

**Comment by LuisM935** [comment]
Motor de Renderizado 3D para Juegos Indie

Gutierrez Martinez JOrge Luis 20210576

**Comment by YabukiD** [comment]
37

**Comment by YuridiaSCH** [comment]
35. Internet de las Cosas (IoT)

**Comment by VaneMG** [comment]
20 - Realidad Aumentada

Millán Guízar Arely Vanessa - 20210599

**Comment by keyemsi** [comment]
Acosta Gutierrez Fabian
40 | Big Data | Sistema de Análisis de Grandes Volúmenes de Datos Meteorológicos 
Construir un sistema capaz de procesar y analizar grandes volúmenes de datos meteorológicos para predecir patrones climáticos.

**Comment by Daniel-Eriberto-ZB** [comment]
1. Generador de Música basado en IA
ZACARIAS BARTOLON DANIEL ERIBERTO #20210653

**Comment by IrvinMP** [comment]
Machine Learning

Irvin Marin Padilla 20210590

**Comment by SergioSG0** [comment]
50. Desarrollo web
Saavedra Galvez Sergio

**Comment by AlvarezKevinDaniel** [comment]
16
Generador de Sitios Web Dinámicos con Tecnologías JAMstack

**Comment by Mildgwey** [comment]
25

**Comment by Kalis-Be** [comment]
Big Data | Herramienta de Visualización de Datos para Análisis de Redes Sociales |   | Desarrollar una herramienta que permita visualizar y analizar grandes volúmenes de datos de redes sociales.

**Comment by JesusMeiker** [comment]
2. Ciberseguridad

Saguilan Roman Jesus

**Comment by GeraMx0** [comment]
14. Simulador de Redes Neuronales para Experimentación Educativa

**Comment by 03Juan2001** [comment]
19 Automatización de Procesos
Bot de Automatización para Procesos Administrativos
Avila Ayala Juan Carlos - 20210546

**Comment by migueszitle111** [comment]
47

**Comment by IoTeacher** [comment]
Hubo 3 entradas borradas por duplicados.

**Comment by 03Juan2001** [comment]
43

**Comment by VaneMG** [comment]
36 | Inteligencia Artificial | Sistema de Tutoría Inteligente para Aprendizaje de Idiomas
 Millán Guízar Arely Vanessa 20210599

**Comment by CarlosMolinaR** [comment]
31

**Comment by Kalis-Be** [comment]
Modelado de datos | Herramienta de Diseño y Simulación de Bases de Datos NoSQL |   | Implementar una herramienta para el diseño y simulación de bases de datos NoSQL para aplicaciones escalables.

**Comment by Kalis-Be** [comment]
33

**Comment by EduardoGV117** [comment]
12 - Visión Computacional
Gonzalez Vejar Juan Eduardo  - 20212934

**Comment by OrdinaryScript** [comment]
35

**Comment by victormillan19** [comment]
12-. Aplicación para el Reconocimiento de Especies de Plantas mediante Imágenes

**Comment by SalvadorEliLopezPartida** [comment]
42 Servicio de Backup y Recuperación de Datos en la Nube
