### ISSUE TITLE
1.1 GIST de Github

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd#3]
![Image](https://github.com/tectijuana/pdd/assets/2523851/010684fa-a0bc-4525-89f8-22e5a75b1c97)
----

# Anteproyecto utilizando ChatGTP https://chat.openai.com/ con CLAUDE para auditarlo https://gemini.google.com/
# Agregar imagen generativa para ilustrarlo. como https://firefly.adobe.com/ o similar CoPilot antes BING
# Alcances y limitantes del proyecto una vez leido
# Dos opciones Lenguaje de programacion para el proyecto.

Todo será en un GIST   via http://gist.github.com

**Comment by IoTeacher** [comment]
![image](https://github.com/tectijuana/pdd/assets/2523851/edcb5cb0-f360-4018-837b-b9a1bb48e74b)

**Comment by Richierl** [comment]
https://gist.github.com/Richierl/c9af234f9345ce9e66d7eec9684cd88a

**Comment by LuisM935** [comment]
https://gist.github.com/LuisM935/b90f7f657f8e5d96bebbfa0d391951e5

**Comment by Beniez-paola** [comment]
https://gist.github.com/Beniez-paola/8bb5804f14f41cf71217aaacbd985fa8

**Comment by 03Juan2001** [comment]
https://gist.github.com/03Juan2001/f658850bab98269dd1b2a9dbc06950f7

**Comment by DamianRS-TEC** [comment]
https://gist.github.com/DamianRS-TEC/56010320b03a46d0233539d52a77b7e9

**Comment by Mildgwey** [comment]
https://gist.github.com/Mildgwey/c64a1ca3e8c5b6ac451a17671eee8bfa

**Comment by SergioSG0** [comment]
https://gist.github.com/SergioSG0/7f76358646b82a43fdddd47c822992e0

**Comment by YuridiaSCH** [comment]
https://gist.github.com/YuridiaSCH/92ec69390db646ea5002c81c3b2540dc

**Comment by DanielGarciaITT** [comment]
https://gist.github.com/DanielGarciaITT/c1af4ff71f43261f349d09516926c874

**Comment by AdrianSR30** [comment]
https://gist.github.com/AdrianSR30/250d1c096d9ed1f0d2ef2d8c3d0007b9

**Comment by migueszitle111** [comment]
https://gist.github.com/migueszitle111/2d6697561da46bfcf3f935bea252abd0

**Comment by denysshdzp** [comment]
https://gist.github.com/denysshdzp/3705a563ca750d93f0c6631307504065

**Comment by Daniel-Eriberto-ZB** [comment]
https://gist.github.com/Daniel-Eriberto-ZB/3b0f86e815362f040bda52aa0dc37f94

**Comment by BearNX** [comment]
https://gist.github.com/BearNX/e9bf77f92ba81a3f82cdbd671d97eb07

**Comment by SergioEstrada14** [comment]
https://gist.github.com/SergioEstrada14/384c4566d172a5ac410ce50b743c0075

**Comment by bugalox** [comment]
https://gist.github.com/bugalox/2a80c661079076b3acf1d182aa5aa83a

**Comment by RogelioCR311** [comment]
https://gist.github.com/RogelioCR311/f5f2466b544f13c8d69738b0966e5345

**Comment by calonch98** [comment]
https://gist.github.com/calonch98/da97a6d3e06ff8ab7ab84af4fd297b00

**Comment by IrvinMP** [comment]
https://gist.github.com/IrvinMP/a6c1185528d960d7f78512720b5a402e

**Comment by SergioMSR09** [comment]
https://gist.github.com/SergioMSR09/e275162d11079662a822680bd8b99796

**Comment by Kalis-Be** [comment]
https://gist.github.com/Kalis-Be/17a396687acea9ab8ca6163420a4c2f7

**Comment by MariaRamosOrtiz** [comment]
https://gist.github.com/MariaRamosOrtiz/139c58f1d31c3b14b5fd53b2e8c47cf7

**Comment by AldoMon99** [comment]
https://gist.github.com/AldoMon99/d6cc5ffb544301998a05234372dec00c

**Comment by Danielusuario** [comment]
https://gist.github.com/Danielusuario/2df69010e5aefde5aff5c3c6da3f8fe8

**Comment by YabukiD** [comment]
https://gist.github.com/YabukiD/3e14c454a7da91fcbf23c772a99d9762

**Comment by CarlosMolinaR** [comment]
https://gist.github.com/CarlosMolinaR/2cf1ecbc78577ceb9307047afd5fd5cc

**Comment by GabrielHernandezZam** [comment]
https://gist.github.com/GabrielHernandezZam/59cfdf25f9e8ae2eee6a2a14ac2f4596

**Comment by Jyuls** [comment]
https://gist.github.com/Jyuls/e025aefcc55d36f32fcb46f4030b7435

**Comment by EduardoGV117** [comment]
https://gist.github.com/EduardoGV117/dc281a3c4222e5d81493ee909becdca2

**Comment by Barny-Claus** [comment]
https://gist.github.com/Barny-Claus/9a891ad16be2190831cf3b8f727ad85e

**Comment by GeraMx0** [comment]
https://gist.github.com/GeraMx0/6822066ae62e28e1410356b500ce1960

**Comment by Gibrahn** [comment]
<script src="https://gist.github.com/Gibrahn/ebab24e93e66fb5a54c619566f8d68c9.js"></script>

**Comment by Gibrahn** [comment]
https://gist.github.com/Gibrahn/ebab24e93e66fb5a54c619566f8d68c9.js

**Comment by xMeiker** [comment]
https://gist.github.com/xMeiker/b7c53a4acd3714412a238e4f7a38928a

**Comment by miguelbct** [comment]
https://gist.github.com/miguelbct/fbe2628e11b6933190ee6c1855caec27

**Comment by AlvarezKevinDaniel** [comment]
https://gist.github.com/AlvarezKevinDaniel/0dc422face22a5ed71978b0a69f8e1b1

**Comment by victormillan19** [comment]
https://gist.github.com/victormillan19/c7c02b4c52c6148034fcb4ad4ce04f2a

**Comment by OrdinaryScript** [comment]
https://gist.github.com/OrdinaryScript/bf5820e676077becbda1450bb8b0b1e6
