### ISSUE TITLE
1.1.1 Entrevista, Anaisis del sistema y seleccion del Leng. de Programacion y BASE de DATOS

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd#4]
Entrevista de los requerimientos del sistema
Análisis del Sistema
Elección de los leng. de programación y otros recursos.

![Image](https://github.com/tectijuana/pdd/assets/2523851/038069a5-f410-4f5c-8841-2b3842d34cd2)

**Comment by IoTeacher** [comment]
# PROMPT
Simular una entrevista con cliente JUAN PEREZ de la Empresa AGRICULTORES VINICOLAS  una empresa QUE ELABORA ABONO ORGANICO Y VENTA SACOS DE TIERRA TRATADA PARA CULTIVO de requiere SISTEMA DE DISTRIBUCION E INVENTARIO con las necesidades actuales  del cliente son: hoja de calculo, email, para agilizar manualmente las entregas, por tal de nuestra asesoria y desarrollo del sistemas, la entrevista va acompañada de necesidades de informacion. Cliente requiere una solucion para atender la productividad de el proyecto.  Cliente desconoce es experto en su area de ________

**Comment by GabrielHernandezZam** [comment]
https://gist.github.com/GabrielHernandezZam/4bb1584e5d64c98a6addbbcaf02c7e92

**Comment by BearNX** [comment]
https://gist.github.com/BearNX/d68dd2c2ded09569074f51512629c936

**Comment by Danielusuario** [comment]
https://gist.github.com/Danielusuario/b685debce4ec8539a130fe69b90d5654

**Comment by YabukiD** [comment]
https://gist.github.com/YabukiD/314b3087d600da8abd51cd5f10204892

**Comment by migueszitle111** [comment]
https://gist.github.com/migueszitle111/e0042bb532bd077c678d4f9f23a48926

**Comment by AdrianSR30** [comment]
https://gist.github.com/AdrianSR30/04444b422a01acc3e60e655b88e57f06

**Comment by SergioSG0** [comment]
https://gist.github.com/SergioSG0/3ca5014dde2ca91da234819c31398ac1

**Comment by Daniel-Eriberto-ZB** [comment]
https://gist.github.com/Daniel-Eriberto-ZB/3aed34df288c34cd70ee9a921618e4c5

**Comment by SergioEstrada14** [comment]
https://gist.github.com/SergioEstrada14/44f73879095979da2269214cd0b8adec

**Comment by RogelioCR311** [comment]
https://gist.github.com/RogelioCR311/b218a093437db4fc770395a5d12c13ca

**Comment by keyemsi** [comment]
https://gist.github.com/keyemsi/eaa37d37aeeaea952acf599d1b39f8e8

**Comment by DamianRS-TEC** [comment]
https://gist.github.com/DamianRS-TEC/1b4e73930a49d30d51e7b01cd41ad0af

**Comment by LuisM935** [comment]
https://gist.github.com/LuisM935/50c002d9bed813d94bf13bcefc0a4c7b

**Comment by IrvinMP** [comment]
https://gist.github.com/IrvinMP/0e80ca6cfaae46c637de47ecc3500103

**Comment by DanielGarciaITT** [comment]
https://gist.github.com/DanielGarciaITT/f801e9e4fc22943c7809aeff8a10b85d

**Comment by CarlosMolinaR** [comment]
https://gist.github.com/CarlosMolinaR/424719ceae172beec7cce20928343136

**Comment by calonch98** [comment]
https://gist.github.com/calonch98/da97a6d3e06ff8ab7ab84af4fd297b00

**Comment by SergioMSR09** [comment]
https://gist.github.com/SergioMSR09/e275162d11079662a822680bd8b99796

**Comment by denysshdzp** [comment]
https://gist.github.com/denysshdzp/8eb467a8103b0952adc1ee474e2fd36d

**Comment by MariaRamosOrtiz** [comment]
https://gist.github.com/MariaRamosOrtiz/139c58f1d31c3b14b5fd53b2e8c47cf7

**Comment by Richierl** [comment]
https://gist.github.com/Richierl/981d7a8983ceeb2682a2b60023706604

**Comment by Beniez-paola** [comment]
https://gist.github.com/Beniez-paola/4b99c8527260c9acabec2e0d491fdc5d

**Comment by AdrianSR30** [comment]
https://gist.github.com/AdrianSR30/04444b422a01acc3e60e655b88e57f06

**Comment by VaneMG** [comment]
https://gist.github.com/VaneMG/227ecd01ee63aa476f55d1f9cf38337b

**Comment by Mildgwey** [comment]
https://gist.github.com/Mildgwey/e643d900e1bc003dd9fb70b58c6fcac6#file-entrevista-md

**Comment by Daniel-Eriberto-ZB** [comment]
https://gist.github.com/Daniel-Eriberto-ZB/3aed34df288c34cd70ee9a921618e4c5

**Comment by Gibrahn** [comment]
https://gist.github.com/Gibrahn/06096d5e6b47b2c8cf95685189730485.js

**Comment by YuridiaSCH** [comment]
https://gist.github.com/YuridiaSCH/92ec69390db646ea5002c81c3b2540dc

**Comment by Barny-Claus** [comment]
https://gist.github.com/Barny-Claus/149e2bf3145ae04af1c70444599bd571

**Comment by migueszitle111** [comment]
https://gist.github.com/migueszitle111/e0042bb532bd077c678d4f9f23a48926

**Comment by Danielusuario** [comment]
https://gist.github.com/Danielusuario/b7a410e748898c6084bc827469f53c75

**Comment by 03Juan2001** [comment]
https://gist.github.com/03Juan2001/0a8c0d9b1c0abe94f001c6b6e7b65475

**Comment by Kalis-Be** [comment]
https://gist.github.com/Kalis-Be/f24b6bfea7d70a015ef323766423cef7

**Comment by SergioEstrada14** [comment]
https://gist.github.com/SergioEstrada14/44f73879095979da2269214cd0b8adec

**Comment by bugalox** [comment]
https://gist.github.com/bugalox/2a80c661079076b3acf1d182aa5aa83a

**Comment by Jyuls** [comment]
https://gist.github.com/Jyuls/88a6f84bce279a8670fac786a9a041e7

**Comment by xMeiker** [comment]
https://gist.github.com/xMeiker/36dedb5e42f0d58025e1468e0c137963

**Comment by GeraMx0** [comment]
https://gist.github.com/GeraMx0/a4674eb06ea60a885af0c1dc053a56c3

**Comment by miguelbct** [comment]
https://gist.github.com/miguelbct/fbe2628e11b6933190ee6c1855caec27

**Comment by GabrielHernandezZam** [comment]
https://gist.github.com/GabrielHernandezZam/4bb1584e5d64c98a6addbbcaf02c7e92

**Comment by xMeiker** [comment]
https://gist.github.com/xMeiker/b7c53a4acd3714412a238e4f7a38928a

**Comment by DrPepperFan** [comment]
https://gist.github.com/DrPepperFan/cdca816fc36358c8d573d1f150a4df37

**Comment by victormillan19** [comment]
https://gist.github.com/victormillan19/c7c02b4c52c6148034fcb4ad4ce04f2a

**Comment by OrdinaryScript** [comment]
https://gist.github.com/OrdinaryScript/fd71fc1c9b413a2f00469c5d4424eab2

**Comment by AlvarezKevinDaniel** [comment]
https://gist.github.com/AlvarezKevinDaniel/0dc422face22a5ed71978b0a69f8e1b1
