### ISSUE TITLE
1.2 LIstar los patrones de diseño de su sistema, use GTP para detectar las clases.

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd#5]
![Image](https://github.com/tectijuana/pdd/assets/2523851/a4ad58e7-d9ce-4e1d-83af-d1ce8c0b8502)

1. Realizar la justificación de las clases del sistema, en contraste a el lenguaje de programación que es el recomendable por el GTP 
2. Localiza la lista de patrones Diseño, del sistema en cuestion.
3. Apoyarse del MERMAID JS  https://mermaid.live/ para un bosquejo de cada uno de los patrones genericamente representados.
4. Determinar el Lenguaje de Programación el cual se recomienda por el GTP dos alternativas

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/pdd/assets/2523851/98c6f38a-b036-4ceb-ad65-0fa149bee135)

**Comment by YuridiaSCH** [comment]
https://gist.github.com/YuridiaSCH/92ec69390db646ea5002c81c3b2540dc

**Comment by keyemsi** [comment]
https://gist.github.com/keyemsi/9475ba9711924668507c46c15f90a86a

**Comment by AdrianSR30** [comment]
https://gist.github.com/AdrianSR30/5ee0d43c87c404de0f3bd0cbe661c880

**Comment by BearNX** [comment]
https://gist.github.com/BearNX/1ca09cc5a5a5aa49df9779bfacad2b11

**Comment by migueszitle111** [comment]
https://gist.github.com/migueszitle111/e0042bb532bd077c678d4f9f23a48926

**Comment by SergioEstrada14** [comment]
https://gist.github.com/SergioEstrada14/44f73879095979da2269214cd0b8adec

**Comment by Richierl** [comment]
https://gist.github.com/Richierl/981d7a8983ceeb2682a2b60023706604

**Comment by calonch98** [comment]
https://gist.github.com/calonch98/da97a6d3e06ff8ab7ab84af4fd297b00

**Comment by GabrielHernandezZam** [comment]
https://gist.github.com/GabrielHernandezZam/4bb1584e5d64c98a6addbbcaf02c7e92

**Comment by SergioSG0** [comment]
https://gist.github.com/SergioSG0/0e050cac1e29219b6bd9c491ae8f02c3

**Comment by CarlosMolinaR** [comment]
https://gist.github.com/CarlosMolinaR/94115fec9c647d9a64ff71732cd35ca4

**Comment by LuisM935** [comment]
https://gist.github.com/LuisM935/2936754332edf9942e67ca3179db173c

**Comment by 03Juan2001** [comment]
https://gist.github.com/03Juan2001/018a2af5d8499898e3e2f51aa6bec1a7

**Comment by Mildgwey** [comment]
https://gist.github.com/Mildgwey/e643d900e1bc003dd9fb70b58c6fcac6

**Comment by Beniez-paola** [comment]
https://gist.github.com/Beniez-paola/4b99c8527260c9acabec2e0d491fdc5d

**Comment by denysshdzp** [comment]
https://gist.github.com/denysshdzp/3238faa567bd40b68722efc9ab67c153

**Comment by CruzEVM** [comment]
https://gist.github.com/CruzEVM/ee5381c5cfd6c7c008331659c61a0925

**Comment by DrPepperFan** [comment]
https://gist.github.com/DrPepperFan/cdca816fc36358c8d573d1f150a4df37

**Comment by MariaRamosOrtiz** [comment]
https://gist.github.com/MariaRamosOrtiz/139c58f1d31c3b14b5fd53b2e8c47cf7

**Comment by VaneMG** [comment]
https://gist.github.com/VaneMG/227ecd01ee63aa476f55d1f9cf38337b

**Comment by Danielusuario** [comment]
https://gist.github.com/Danielusuario/b685debce4ec8539a130fe69b90d5654

**Comment by YabukiD** [comment]
https://gist.github.com/YabukiD/b0ffa22b85fbeb62985b6312e02a2926

**Comment by Daniel-Eriberto-ZB** [comment]
https://gist.github.com/Daniel-Eriberto-ZB/dc113f599f9d51509a2e13b3e585f29d

**Comment by bugalox** [comment]
https://gist.github.com/bugalox/2a80c661079076b3acf1d182aa5aa83a

**Comment by Gibrahn** [comment]
https://gist.github.com/Gibrahn/c7803f0e00626a32b1e2a2a619397179

**Comment by Barny-Claus** [comment]
https://gist.github.com/Barny-Claus/66648579f22396be300ff8457f0e6c83

**Comment by xMeiker** [comment]
https://gist.github.com/xMeiker/b7c53a4acd3714412a238e4f7a38928a

**Comment by EduardoGV117** [comment]
https://gist.github.com/EduardoGV117/dc281a3c4222e5d81493ee909becdca2

**Comment by DanielGarciaITT** [comment]
https://gist.github.com/DanielGarciaITT/f801e9e4fc22943c7809aeff8a10b85d

**Comment by IrvinMP** [comment]
https://gist.github.com/IrvinMP/9144c397ec700e29e7e0478f25aadf6d

**Comment by GeraMx0** [comment]
https://gist.github.com/GeraMx0/a4674eb06ea60a885af0c1dc053a56c3

**Comment by victormillan19** [comment]
https://gist.github.com/victormillan19/c7c02b4c52c6148034fcb4ad4ce04f2a

**Comment by AlvarezKevinDaniel** [comment]
https://gist.github.com/AlvarezKevinDaniel/0dc422face22a5ed71978b0a69f8e1b1
