### ISSUE TITLE
1.3 Patrones de diseño Originales (java)

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd#6]
![Image](https://github.com/tectijuana/pdd/assets/2523851/88018971-7052-4abd-b50b-9e48abc8a69d)

![](https://miro.medium.com/v2/resize:fit:1400/format:webp/1*HRmtM1gp10Ez1ywqF553BQ.png)

Los Patrones de Diseño de GoF (Gang of Four, o "Cuadrilla de los Cuatro") se refieren a una colección de soluciones reusables a problemas comunes en el diseño de software. Esta colección fue popularizada por el libro "Design Patterns: Elements of Reusable Object-Oriented Software", publicado en 1994 por cuatro autores: Erich Gamma, Richard Helm, Ralph Johnson y John Vlissides, quienes son colectivamente conocidos como el "Gang of Four".

Patrones de diseño creacional
-Patrón singleton
-Patrón de método de fábrica
-Patrón abstracto de fábrica
-Patrón de constructor
-Patrón de prototipo
Patrones de diseño estructural
-Patrón de adaptador
-Patrón decorador
-Patrón de fachada
-Patrón de proxy
Patrones de diseño de comportamiento
-Patrón de cadena de responsabilidad
-Patrón iterador
-Patrón de observador

Ejercicio:

https://www.freecodecamp.org/news/javascript-design-patterns-explained/

Pasar a Mermaid JS los patrones clasicos

**Comment by IoTeacher** [comment]
![Image](https://github.com/tectijuana/pdd/assets/2523851/f9af5a9a-f323-4044-bb2a-7f47aadb4515)



https://classroom.github.com/a/pr55C16z

**Comment by YuridiaSCH** [comment]
https://github.com/tectijuana/pdd-javascript-YuridiaSCH

**Comment by bugalox** [comment]
https://gist.github.com/bugalox/2a80c661079076b3acf1d182aa5aa83a

**Comment by Beniez-paola** [comment]
https://github.com/tectijuana/pdd-javascript-Beniez-paola

**Comment by YabukiD** [comment]
https://github.com/tectijuana/pdd-javascript-YabukiD 
https://gist.github.com/YabukiD/148e1df5d8e745bf1369c2d9f8eff8a0

**Comment by AdrianSR30** [comment]
https://github.com/tectijuana/pdd-javascript-AdrianSR30

**Comment by migueszitle111** [comment]
https://github.com/tectijuana/pdd-javascript-migueszitle111

**Comment by 03Juan2001** [comment]
https://github.com/tectijuana/pdd-javascript-03Juan2001

**Comment by Richierl** [comment]
https://github.com/tectijuana/pdd-javascript-Richierl

**Comment by GabrielHernandezZam** [comment]
https://github.com/tectijuana/pdd-javascript-GabrielHernandezZam/blob/main/README.md

**Comment by VaneMG** [comment]
https://gist.github.com/VaneMG/227ecd01ee63aa476f55d1f9cf38337b

**Comment by Daniel-Eriberto-ZB** [comment]
https://github.com/tectijuana/pdd-javascript-Daniel-Eriberto-ZB

**Comment by Danielusuario** [comment]
https://github.com/tectijuana/pdd-javascript-Danielusuario

**Comment by Mildgwey** [comment]
https://github.com/tectijuana/pdd-javascript-Mildgwey/blob/main/README.md

**Comment by IrvinMP** [comment]
https://github.com/tectijuana/pdd-javascript-IrvinMP/tree/main

**Comment by BearNX** [comment]
https://gist.github.com/BearNX/ac57c1dc704b6f38332a0bf09adb601b

**Comment by xMeiker** [comment]
https://gist.github.com/xMeiker/b7c53a4acd3714412a238e4f7a38928a

**Comment by CarlosMolinaR** [comment]
https://github.com/tectijuana/pdd-javascript-CarlosMolinaR

**Comment by Barny-Claus** [comment]
https://github.com/tectijuana/pdd-javascript-Barny-Claus/tree/main

**Comment by DrPepperFan** [comment]
https://github.com/tectijuana/pdd-javascript-DrPepperFan

**Comment by LuisM935** [comment]
https://github.com/tectijuana/pdd-javascript-LuisM935

**Comment by GeraMx0** [comment]
https://gist.github.com/GeraMx0/a4674eb06ea60a885af0c1dc053a56c3

**Comment by victormillan19** [comment]
https://github.com/tectijuana/pdd-javascript-victormillan19

https://gist.github.com/victormillan19/c7c02b4c52c6148034fcb4ad4ce04f2a

**Comment by denysshdzp** [comment]
https://github.com/tectijuana/pdd-javascript-denysshdzp/tree/main

**Comment by AlvarezKevinDaniel** [comment]
https://github.com/tectijuana/pdd-javascript-AlvarezKevinDaniel/tree/main
