### ISSUE TITLE
1.5 EXAMEN T1-Sistema ( CIERRA 11:59pm jueves 7-mrz) no se aceptan repos personales.

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd#8]
![Image](https://github.com/tectijuana/pdd/assets/2523851/04675884-f5a5-49e3-aebe-cfc9d1ae5136)

Para entregar el JUEVES se invierte 3 hrs para finalizarlo que son la semana de clase.

Repositorio a clonar es:

https://classroom.github.com/a/7d-CG3PI

Recuerde el enfoque es su sistema en cuestión darle un orden serio dentro de la información que se recolecto en la quincena, se estima que UD tiene el 70% realizado en secciones GIST, pero esta inversión de tiempo es que este en compañía del transformador  GTP para darle originalidad a el sistema, quedando como un plano general del sistema a realizar.

Rubrica:

80% Complementar la estructura en Markdown (html, o mixto), lógica de la redacción y atención a el documento segun las indicaciones pertinentes.
20% Diagramas e ilustraciones técnica del área de modelado exclusivamente con el programa de Visual Paradigm (recomendable)

NOTA: La entrega es privada en su respectivo GitHub Classroom.

**Comment by BearNX** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-BearNX

**Comment by Beniez-paola** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-Beniez-paola

**Comment by Mildgwey** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-Mildgwey

**Comment by YuridiaSCH** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-YuridiaSCH

**Comment by Barny-Claus** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-Barny-Claus

**Comment by Richierl** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-Richierl

**Comment by VaneMG** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-VaneMG

**Comment by bugalox** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-bugalox

**Comment by Danielusuario** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-Danielusuario

**Comment by Danielusuario** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-Danielusuario

**Comment by Jyuls** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-Jyuls/blob/main/examen.md

**Comment by victormillan19** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-victormillan19/blob/main/README.md

**Comment by keyemsi** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-keyemsi/edit/main/README.md

**Comment by LuisM935** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-LuisM935

**Comment by GabrielHernandezZam** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-GabrielHernandezZam/blob/main/Examen.md

**Comment by CarlosMolinaR** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-CarlosMolinaR

**Comment by miguelbct** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-miguelbct/tree/main

**Comment by CruzEVM** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-CruzEVM.git

**Comment by DrPepperFan** [comment]
https://github.com/DrPepperFan/24apddexamen1-sistema-DrPepperFan/tree/patch-2

**Comment by MariaRamosOrtiz** [comment]
https://github.com/MariaRamosOrtiz/24apddexamen1-sistema-MariaRamosOrtiz

**Comment by denysshdzp** [comment]
https://github.com/denysshdzp/24apddexamen1-sistema-denysshdzp/blob/main/README.md

**Comment by denysshdzp** [comment]
https://github.com/denysshdzp/24apddexamen1-sistema-denysshdzp

**Comment by GeraMx0** [comment]
https://github.com/GeraMx0/24apddexamen1-sistema-GeraMx0

**Comment by Kalis-Be** [comment]
https://github.com/Kalis-Be/24apddexamen1-sistema-Kalis-Be/blob/main/README.md

**Comment by IrvinMP** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-IrvinMP

**Comment by YabukiD** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-YabukiD

**Comment by xMeiker** [comment]
https://github.com/tectijuana/24apddexamen1-sistema-xMeiker

**Comment by IoTeacher** [comment]
80% - Estructura en Markdown (html, o mixto) y Lógica de Redacción:

Claridad (20%): El documento debe ser claro y comprensible. La información debe ser presentada de forma lógica y coherente. Las secciones y subsecciones deben estar bien definidas, y debe ser fácil navegar a través del documento.
Integridad (20%): Revisa si todos los aspectos relevantes del sistema están cubiertos. Deberías tener secciones que expliquen claramente los requisitos del sistema, tanto funcionales como no funcionales, así como la arquitectura del sistema, casos de uso, y cualquier otro componente necesario.
Exactitud (20%): Asegúrate de que la información proporcionada sea precisa y esté actualizada. Verifica que los datos técnicos y las especificaciones del sistema sean correctos.
Redacción y Gramática (10%): El documento debe estar bien escrito, sin errores de ortografía o gramaticales que puedan dificultar la comprensión. La consistencia en la terminología técnica y el estilo de redacción es crucial.
Atención a las Indicaciones (10%): El documento debe seguir todas las indicaciones y requerimientos especificados, incluyendo la estructura, formato y cualquier directriz específica proporcionada.
20% - Diagramas e Ilustraciones Técnicas:

Representación Técnica (10%): Los diagramas deben ser técnicamente correctos y representar de manera precisa la arquitectura del sistema, los flujos de datos, las interacciones entre los componentes y otros aspectos técnicos relevantes.
Calidad Visual (5%): Los diagramas deben ser visualmente claros y profesionales. Deben ser fáciles de leer y entender, con un buen uso de colores, símbolos y texto.
Uso de Herramientas (5%): Deben utilizarse las herramientas recomendadas, en este caso Visual Paradigm, para garantizar la calidad y la consistencia de los diagramas e ilustraciones técnicas.

**Comment by IoTeacher** [comment]
## 80% - Estructura en Markdown (html, o mixto) y Lógica de Redacción:

- **Claridad (20%)**: El documento debe ser claro y comprensible. La información debe ser presentada de forma lógica y coherente. Las secciones y subsecciones deben estar bien definidas, y debe ser fácil navegar a través del documento.
- **Integridad (20%)**: Revisa si todos los aspectos relevantes del sistema están cubiertos. Deberías tener secciones que expliquen claramente los requisitos del sistema, tanto funcionales como no funcionales, así como la arquitectura del sistema, casos de uso, y cualquier otro componente necesario.
- **Exactitud (20%)**: Asegúrate de que la información proporcionada sea precisa y esté actualizada. Verifica que los datos técnicos y las especificaciones del sistema sean correctos.
- **Redacción y Gramática (10%)**: El documento debe estar bien escrito, sin errores de ortografía o gramaticales que puedan dificultar la comprensión. La consistencia en la terminología técnica y el estilo de redacción es crucial.
- **Atención a las Indicaciones (10%)**: El documento debe seguir todas las indicaciones y requerimientos especificados, incluyendo la estructura, formato y cualquier directriz específica proporcionada.

## 20% - Diagramas e Ilustraciones Técnicas:

- **Representación Técnica (10%)**: Los diagramas deben ser técnicamente correctos y representar de manera precisa la arquitectura del sistema, los flujos de datos, las interacciones entre los componentes y otros aspectos técnicos relevantes.
- **Calidad Visual (5%)**: Los diagramas deben ser visualmente claros y profesionales. Deben ser fáciles de leer y entender, con un buen uso de colores, símbolos y texto.
- **Uso de Herramientas (5%)**: Deben utilizarse las herramientas recomendadas, en este caso Visual Paradigm, para garantizar la calidad y la consistencia de los diagramas e ilustraciones técnicas.
